
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Dominik
 */
public class Kalkulacka extends javax.swing.JFrame {

    /**
     * Creates new form kalkukacja
     */
    public Kalkulacka() {
        initComponents();
        
        //get decimal separator and set it to this one
        DecimalFormat format=(DecimalFormat) DecimalFormat.getInstance();
        DecimalFormatSymbols symbols=format.getDecimalFormatSymbols();
        char sep=symbols.getDecimalSeparator();       
        jButton9.setText(Character.toString(sep));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton14 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jButton15 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kalkulačka");

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setName("textPole"); // NOI18N

        jButton14.setText("=");
        jButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton14MouseReleased(evt);
            }
        });

        jButton15.setText("X");
        jButton15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton15MouseReleased(evt);
            }
        });

        jButton5.setLabel("4");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton5MouseReleased(evt);
            }
        });

        jButton8.setLabel("9");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton8MouseReleased(evt);
            }
        });

        jButton12.setText("+");
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton12MouseReleased(evt);
            }
        });

        jButton13.setText("-");
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton13MouseReleased(evt);
            }
        });

        jButton4.setLabel("5");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton4MouseReleased(evt);
            }
        });

        jButton9.setText(".");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton9MouseReleased(evt);
            }
        });

        jButton7.setText("0");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton7MouseReleased(evt);
            }
        });

        jButton2.setText("CE");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton2MouseReleased(evt);
            }
        });

        jButton10.setLabel("8");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton10MouseReleased(evt);
            }
        });

        jButton1.setText("1");
        jButton1.setName("1"); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tlacitkoCislaReleased(evt);
            }
        });

        jButton11.setLabel("3");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton11MouseReleased(evt);
            }
        });

        jButton6.setLabel("6");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton6MouseReleased(evt);
            }
        });

        jButton3.setLabel("2");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton3MouseReleased(evt);
            }
        });

        jButton16.setText(":");
        jButton16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton16MouseReleased(evt);
            }
        });

        jButton17.setLabel("7");
        jButton17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton17MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(164, Short.MAX_VALUE))
        );

        jDesktopPane1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton10, jButton11, jButton12, jButton13, jButton15, jButton16, jButton2, jButton3, jButton4, jButton5, jButton6, jButton7, jButton8, jButton9});

        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jDesktopPane1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButton10, jButton11, jButton12, jButton13, jButton15, jButton16, jButton2, jButton3, jButton4, jButton5, jButton6, jButton7, jButton8, jButton9});

        jDesktopPane1.setLayer(jButton15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton17, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDesktopPane1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton14, jDesktopPane1, jTextField1});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This method is called after pressing button 1
     * if this is the first number it clears text field
     * if it isn't first it just adds this number after previous in the text field
     * @param evt Mouse Released event
     */
    private void tlacitkoCislaReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tlacitkoCislaReleased
        if (jePrvni == true) {
            jTextField1.setText("");
            jTextField1.setText(jTextField1.getText() + ((javax.swing.JButton) evt.getSource()).getText());//get text from button
            jePrvni = false;
        } else {
            jTextField1.setText(jTextField1.getText() + ((javax.swing.JButton) evt.getSource()).getText());//get text from button           
        }     
    }//GEN-LAST:event_tlacitkoCislaReleased
    
    /**
     * This method is called after pressing button 1
     * if this is the first number it clears text field
     * if it isn't first it just adds this number after previous in the text field
     * @param evt Mouse Released event
     */
    private void jButton3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseReleased
       if (jePrvni == true) {
            jTextField1.setText("");
            jTextField1.setText(jTextField1.getText() + ((javax.swing.JButton) evt.getSource()).getText());//get text from button
            jePrvni = false;
        } else {
            jTextField1.setText(jTextField1.getText() + ((javax.swing.JButton) evt.getSource()).getText());//get text from button           
        }
    }//GEN-LAST:event_jButton3MouseReleased

    /**
     * This method clears the text field and resets variables
     * @param evt mouse released event
     */
    private void jButton2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseReleased
        jTextField1.setText("");//clear
        prvniCislo = 0.0;
        druheCislo = 0.0;
        jeCarka = false;
        vysledek = 0.0;
        //operace = "";
        jePrvni = true;
    }//GEN-LAST:event_jButton2MouseReleased
    
    /**
     * This method is called after pressing button 1
     * if this is the first number it clears text field
     * if it isn't first it just adds this number after previous in the text field
     * @param evt Mouse Released event
     */
    private void jButton5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseReleased
        if (jePrvni == true) {
            jTextField1.setText("");
            jTextField1.setText(jTextField1.getText() + ((javax.swing.JButton) evt.getSource()).getText());//get text from button
            jePrvni = false;
        } else {
            jTextField1.setText(jTextField1.getText() + ((javax.swing.JButton) evt.getSource()).getText());//get text from button           
        }
    }//GEN-LAST:event_jButton5MouseReleased

    /**
     * This method is called after pressing button 1
     * if this is the first number it clears text field
     * if it isn't first it just adds this number after previous in the text field
     * @param evt Mouse Released event
     */
    private void jButton4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseReleased
        if (jePrvni == true) {
            jTextField1.setText("");
            jTextField1.setText(jTextField1.getText() + ((javax.swing.JButton) evt.getSource()).getText());//get text from button
            jePrvni = false;
        } else {
            jTextField1.setText(jTextField1.getText() + ((javax.swing.JButton) evt.getSource()).getText());//get text from button           
        }
    }//GEN-LAST:event_jButton4MouseReleased

    /**
     * This method is called after pressing button 1
     * if this is the first number it clears text field
     * if it isn't first it just adds this number after previous in the text field
     * @param evt Mouse Released event
     */
    private void jButton6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseReleased
        if (jePrvni == true) {
            jTextField1.setText("");
            jTextField1.setText(jTextField1.getText() + ((javax.swing.JButton) evt.getSource()).getText());//get text from button
            jePrvni = false;
        } else {
            jTextField1.setText(jTextField1.getText() + ((javax.swing.JButton) evt.getSource()).getText());//get text from button           
        }
    }//GEN-LAST:event_jButton6MouseReleased

    /**
     * This method adds colomn if it is not in first place and the is not any present currently
     * @param evt mouse released event
     */
    private void jButton9MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseReleased
        if (jePrvni == false) {
            if (jeCarka == false) { // neni carka
                jTextField1.setText(jTextField1.getText() + ".");//put in colomn
                jeCarka = true;
            }
        }     
    }//GEN-LAST:event_jButton9MouseReleased

    /**
     * This method is called after pressing button 1
     * if this is the first number it clears text field
     * if it isn't first it just adds this number after previous in the text field
     * @param evt Mouse Released event
     */
    private void jButton7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseReleased
        if (jePrvni == true) {
            jTextField1.setText("");
            jTextField1.setText(jTextField1.getText() + ((javax.swing.JButton) evt.getSource()).getText());//get text from button
            jePrvni = false;
        } else {
            jTextField1.setText(jTextField1.getText() + ((javax.swing.JButton) evt.getSource()).getText());//get text from button           
        }
    }//GEN-LAST:event_jButton7MouseReleased

    /**
     * This method is called after pressing button 1
     * if this is the first number it clears text field
     * if it isn't first it just adds this number after previous in the text field
     * @param evt Mouse Released event
     */
    private void jButton10MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseReleased
        if (jePrvni == true) {
            jTextField1.setText("");
            jTextField1.setText(jTextField1.getText() + ((javax.swing.JButton) evt.getSource()).getText());//get text from button
            jePrvni = false;
        } else {
            jTextField1.setText(jTextField1.getText() + ((javax.swing.JButton) evt.getSource()).getText());//get text from button           
        }
    }//GEN-LAST:event_jButton10MouseReleased

    /**
     * This method is called after pressing button 1
     * if this is the first number it clears text field
     * if it isn't first it just adds this number after previous in the text field
     * @param evt Mouse Released event
     */
    private void jButton8MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseReleased
        if (jePrvni == true) {
            jTextField1.setText("");
            jTextField1.setText(jTextField1.getText() + ((javax.swing.JButton) evt.getSource()).getText());//get text from button
            jePrvni = false;
        } else {
            jTextField1.setText(jTextField1.getText() + ((javax.swing.JButton) evt.getSource()).getText());//get text from button           
        }
    }//GEN-LAST:event_jButton8MouseReleased

    /**
     * This method is called after pressing button 1
     * if this is the first number it clears text field
     * if it isn't first it just adds this number after previous in the text field
     * @param evt Mouse Released event
     */
    private void jButton11MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseReleased
        if (jePrvni == true) {
            jTextField1.setText("");
            jTextField1.setText(jTextField1.getText() + ((javax.swing.JButton) evt.getSource()).getText());//get text from button
            jePrvni = false;
        } else {
            jTextField1.setText(jTextField1.getText() + ((javax.swing.JButton) evt.getSource()).getText());//get text from button           
        }
    }//GEN-LAST:event_jButton11MouseReleased

     /**
     * This method sets operation to add
     * @param evt mouse released event
     */
    private void jButton12MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseReleased
        // +
        prvniCislo = Double.parseDouble(jTextField1.getText());
       // jTextField1.setText("");
        operace = "+";
        jeCarka = false;
        jePrvni = true;
    }//GEN-LAST:event_jButton12MouseReleased

     /**
     * This method sets operation to subtract
     * @param evt mouse released event
     */
    private void jButton13MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseReleased
        prvniCislo = Double.parseDouble(jTextField1.getText());
        //jTextField1.setText("");
        operace = "-";
        jeCarka = false;
        jePrvni = true;
    }//GEN-LAST:event_jButton13MouseReleased

    /**
     * This method resolves mathematical operations set by previous actions and sets
     * variables back to their initial values
     * @param evt mouse released event
     */
    private void jButton14MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton14MouseReleased
        druheCislo = Double.parseDouble(jTextField1.getText());
        //druheCislo -= prvniCislo * Math.pow(10, Double.toString(prvniCislo).length() - jTextField1.getText().length()); 
        switch (operace) {
            case "+":
                vysledek = prvniCislo + druheCislo;
                prvniCislo = 0;
                druheCislo = 0;
                jeCarka = false;
                jTextField1.setText(Double.toString(vysledek));//mainClass.zkratCislo(vysledek, 12))
                vysledek = 0;
                break;
            case "-":
                vysledek = prvniCislo - druheCislo;
                prvniCislo = 0;
                druheCislo = 0;
                jeCarka = false;
                jTextField1.setText(Double.toString(vysledek));
                vysledek = 0;
                break;
            case "*":
                vysledek = prvniCislo * druheCislo;
                prvniCislo = 0;
                druheCislo = 0;
                jeCarka = false;
                jTextField1.setText(Double.toString(vysledek));
                vysledek = 0;
                break;
            case "/":
                if (druheCislo != 0) {
                    vysledek = prvniCislo / druheCislo;
                    prvniCislo = 0;
                    druheCislo = 0;
                    jeCarka = false;
                    jTextField1.setText(Double.toString(vysledek));
                    vysledek = 0;
                } else {
                    jTextField1.setText("Nelze delit 0 !!!");
                    prvniCislo = 0;
                    druheCislo = 0;
                    jeCarka = false;
                    vysledek = 0;
                }
                break;
            default:
                    //jTextField1.setText("");
                break;
        }
        operace = "";
        jePrvni = true;
    }//GEN-LAST:event_jButton14MouseReleased

     /**
     * This method sets operation to multiply
     * @param evt mouse released event
     */
    private void jButton15MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton15MouseReleased
        prvniCislo = Double.parseDouble(jTextField1.getText());
       // jTextField1.setText("");
        operace = "*";
        jeCarka = false;
        jePrvni = true;
    }//GEN-LAST:event_jButton15MouseReleased

    /**
     * This method sets operation to divide
     * @param evt mouse released event
     */
    private void jButton16MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton16MouseReleased
        prvniCislo = Double.parseDouble(jTextField1.getText());
        //jTextField1.setText("");
        operace = "/";
        jeCarka = false;
        jePrvni = true;
    }//GEN-LAST:event_jButton16MouseReleased

    /**
     * This method is called after pressing button 7
     * if this is the first number it clears text field
     * if it isn't first it just adds this number after previous in the text field
     * @param evt Mouse Released event
     */
    private void jButton17MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton17MouseReleased
        if (jePrvni == true) {
            jTextField1.setText("");
            jTextField1.setText(jTextField1.getText() + ((javax.swing.JButton) evt.getSource()).getText());//get text from button
            jePrvni = false;
        } else {
            jTextField1.setText(jTextField1.getText() + ((javax.swing.JButton) evt.getSource()).getText());//get text from button           
        }
    }//GEN-LAST:event_jButton17MouseReleased
 
    
    private double prvniCislo = 0;  //first number variable
    private double druheCislo = 0;  //second number variable
    private double vysledek = 0;    //final number variable
    private String operace = "";    //operation string
    private boolean jeCarka = false;
    private boolean jePrvni = false;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
